# Generated by Django 3.2.4 on 2021-06-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('work_title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('work_type', models.CharField(choices=[('FT', 'Fulltime'), ('PT', 'Parttime'), ('TP', 'Temporary'), ('CT', 'Consultant')], default='FT', max_length=2)),
                ('weekly_hours', models.IntegerField(max_length=2)),
                ('localy_bound', models.BooleanField(default=True)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.CharField(max_length=3000)),
                ('cv_link', models.URLField(max_length=500)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs_backend.user')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs_backend.posting')),
            ],
        ),
    ]
