# Generated by Django 3.2.4 on 2021-06-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='alex@alex.se', max_length=254),
            preserve_default=False,
        ),
    ]
