# Generated by Django 3.2.4 on 2021-06-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='weekly_hours',
            field=models.IntegerField(),
        ),
    ]
