# Generated by Django 3.2.4 on 2021-06-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_backend', '0002_auto_20210618_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
