# Generated by Django 3.2.4 on 2021-06-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_backend', '0004_remove_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
    ]
