# Generated by Django 3.2.4 on 2021-06-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_backend', '0005_remove_user_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
