# Generated by Django 3.2.4 on 2021-06-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_backend', '0006_user_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
