# Generated by Django 3.2.4 on 2021-06-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_backend', '0011_alter_application_cv_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv_link',
            field=models.URLField(max_length=500),
        ),
    ]
