# Generated by Django 3.2.4 on 2021-06-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_backend', '0012_alter_application_cv_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('posting', 'email')},
        ),
    ]
