# Generated by Django 3.2.4 on 2021-06-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_backend', '0013_auto_20210629_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='title',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='posting',
            name='work_title',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
