# Generated by Django 3.2.4 on 2021-08-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
    ]
